import Foundation
import Combine

/// The single source of truth for partners, interactions, reminders and chat.
/// Persists the whole graph to one JSON file in Application Support.
@MainActor
final class DataStore: ObservableObject {
    @Published var partners: [Partner]
    @Published var interactions: [Interaction]
    @Published var reminders: [Reminder]
    @Published var chat: [ChatMessage]

    private static let filename = "data.json"

    init() {
        if let bundle = Persistence.load(DataBundle.self, from: Self.filename) {
            partners = bundle.partners
            interactions = bundle.interactions
            reminders = bundle.reminders
            chat = bundle.chat
        } else {
            let seed = SampleData.makeSeed()
            partners = seed.partners
            interactions = seed.interactions
            reminders = seed.reminders
            chat = []
            Persistence.save(DataBundle(partners: seed.partners,
                                        interactions: seed.interactions,
                                        reminders: seed.reminders,
                                        chat: []),
                             to: Self.filename)
        }
    }

    func save() {
        Persistence.save(DataBundle(partners: partners, interactions: interactions, reminders: reminders, chat: chat),
                         to: Self.filename)
    }

    // MARK: - Partners

    func partner(_ id: UUID?) -> Partner? {
        guard let id else { return nil }
        return partners.first { $0.id == id }
    }

    func addPartner(_ partner: Partner) {
        partners.append(partner)
        save()
    }

    func updatePartner(_ partner: Partner) {
        if let idx = partners.firstIndex(where: { $0.id == partner.id }) {
            partners[idx] = partner
            save()
        }
    }

    func deletePartner(_ partner: Partner) {
        partners.removeAll { $0.id == partner.id }
        interactions.removeAll { $0.partnerId == partner.id }
        reminders.removeAll { $0.partnerId == partner.id }
        save()
    }

    // MARK: - Interactions

    func interactionsForPartner(_ partnerId: UUID) -> [Interaction] {
        interactions.filter { $0.partnerId == partnerId }.sorted { $0.createdAt > $1.createdAt }
    }

    func addInteraction(_ interaction: Interaction) {
        interactions.append(interaction)
        save()
    }

    func updateInteraction(_ interaction: Interaction) {
        if let idx = interactions.firstIndex(where: { $0.id == interaction.id }) {
            interactions[idx] = interaction
            save()
        }
    }

    var recentInteractions: [Interaction] {
        interactions.sorted { $0.createdAt > $1.createdAt }
    }

    // MARK: - Reminders

    func remindersForPartner(_ partnerId: UUID) -> [Reminder] {
        reminders.filter { $0.partnerId == partnerId }.sorted(by: Self.reminderSort)
    }

    func addReminder(_ reminder: Reminder) {
        reminders.insert(reminder, at: 0)
        save()
    }

    func addReminders(_ new: [Reminder]) {
        guard !new.isEmpty else { return }
        reminders.insert(contentsOf: new, at: 0)
        save()
    }

    func setDone(_ reminder: Reminder, _ done: Bool) {
        if let idx = reminders.firstIndex(where: { $0.id == reminder.id }) {
            reminders[idx].isDone = done
            save()
        }
    }

    func toggleReminder(_ reminder: Reminder) {
        setDone(reminder, !reminder.isDone)
    }

    func deleteReminder(_ reminder: Reminder) {
        reminders.removeAll { $0.id == reminder.id }
        save()
    }

    /// Replaces auto-generated follow-up reminders for a partner with a fresh set,
    /// so re-processing a note doesn't pile up duplicates.
    func replaceAutoReminders(for partnerId: UUID, with new: [Reminder]) {
        reminders.removeAll { $0.partnerId == partnerId && $0.isAutoGenerated && !$0.isDone }
        reminders.insert(contentsOf: new, at: 0)
        save()
    }

    var openReminders: [Reminder] {
        reminders.filter { !$0.isDone }.sorted(by: Self.reminderSort)
    }

    var completedReminders: [Reminder] {
        reminders.filter { $0.isDone }.sorted { ($0.dueDate ?? .distantPast) > ($1.dueDate ?? .distantPast) }
    }

    var todayFocus: [Reminder] {
        openReminders.filter { $0.isOverdue || $0.isDueToday || $0.dueDate == nil }
    }

    var upcomingReminders: [Reminder] {
        openReminders.filter {
            guard let due = $0.dueDate else { return false }
            return due > Date() && !$0.isDueToday
        }
    }

    private static func reminderSort(_ a: Reminder, _ b: Reminder) -> Bool {
        if a.isOverdue != b.isOverdue { return a.isOverdue && !b.isOverdue }
        switch (a.dueDate, b.dueDate) {
        case let (.some(da), .some(db)) where da != db:
            return da < db
        case (.some, .none):
            return true
        case (.none, .some):
            return false
        default:
            break
        }
        return a.priority > b.priority
    }

    // MARK: - Chat

    func appendChat(_ message: ChatMessage) {
        chat.append(message)
        save()
    }

    func updateChatMessage(id: UUID, text: String) {
        if let idx = chat.firstIndex(where: { $0.id == id }) {
            chat[idx].text = text
        }
    }

    func removeChatMessage(id: UUID) {
        chat.removeAll { $0.id == id }
        save()
    }

    func clearChat() {
        chat.removeAll()
        save()
    }

    // MARK: - Pipeline analytics

    func count(for stage: PipelineStage) -> Int {
        partners.filter { $0.stage == stage }.count
    }

    var activePartners: [Partner] {
        partners.filter { $0.stage != .lost }
    }

    var signedPartnersCount: Int {
        partners.filter { $0.stage == .partner }.count
    }

    var averageInterest: Int {
        let scope = partners.filter { $0.stage != .lost && $0.stage != .partner }
        guard !scope.isEmpty else { return 0 }
        return Int((Double(scope.map(\.interestScore).reduce(0, +)) / Double(scope.count)).rounded())
    }

    var risingPartners: [Partner] {
        partners
            .filter { $0.momentum == .rising && $0.stage != .partner && $0.stage != .lost }
            .sorted { $0.interestScore > $1.interestScore }
    }

    var coolingPartners: [Partner] {
        partners
            .filter { ($0.momentum == .cooling || $0.momentum == .stalled) && $0.stage != .lost && $0.stage != .partner }
            .sorted { $0.interestScore < $1.interestScore }
    }

    // MARK: - Export / reset

    func exportJSON() -> String {
        Persistence.encodedString(DataBundle(partners: partners, interactions: interactions, reminders: reminders, chat: chat))
    }

    func resetAll() {
        partners = []
        interactions = []
        reminders = []
        chat = []
        save()
    }

    private struct DataBundle: Codable {
        var partners: [Partner]
        var interactions: [Interaction]
        var reminders: [Reminder]
        var chat: [ChatMessage]
    }
}
