import Foundation

/// A strategically designed focus point — the core deliverable of the app.
/// Most are generated automatically by the Follow-up & Strategist agents,
/// but the founders can also add their own.
struct Reminder: Codable, Identifiable, Hashable {
    var id: UUID = UUID()
    var partnerId: UUID?
    var partnerName: String
    var title: String
    var detail: String
    var dueDate: Date?
    var priority: Priority
    var type: ReminderType
    var isDone: Bool
    var isAutoGenerated: Bool
    var createdAt: Date

    init(id: UUID = UUID(),
         partnerId: UUID? = nil,
         partnerName: String = "",
         title: String,
         detail: String = "",
         dueDate: Date? = nil,
         priority: Priority = .medium,
         type: ReminderType = .followUp,
         isDone: Bool = false,
         isAutoGenerated: Bool = true,
         createdAt: Date = Date()) {
        self.id = id
        self.partnerId = partnerId
        self.partnerName = partnerName
        self.title = title
        self.detail = detail
        self.dueDate = dueDate
        self.priority = priority
        self.type = type
        self.isDone = isDone
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
    }

    var isOverdue: Bool {
        guard let due = dueDate, !isDone else { return false }
        return due < Calendar.current.startOfDay(for: Date())
    }

    var isDueToday: Bool {
        guard let due = dueDate else { return false }
        return Calendar.current.isDateInToday(due)
    }
}
